spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/datahub_db
    username: datahub
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true